### PR TITLE
add handlebars.enabled property

### PR DESCRIPTION
**Pull request by uuidcode**
https://github.com/allegro/handlebars-spring-boot-starter/issues/17

### CODE REVIEW

**Comment by uuidcode** [comment]
local testing is OK, but it's fail on Travis. 
I have some wrong?

**Comment by platan** [comment]
Please look at build log https://travis-ci.org/allegro/handlebars-spring-boot-starter/jobs/109025721:
`CodeNarc rule violations were found. See the report at: file:///home/travis/build/allegro/handlebars-spring-boot-starter/build/reports/codenarc/test.html
`
Run `./gradlew check` locally and fix codenarc issues.

**Comment by uuidcode** [comment]
@platan Thanks. I fixed it.

**Comment by plesiecki** [comment]
@uuidcode Would you mind updating the readme as well?

**Comment by uuidcode** [comment]
@plesiecki I updated it. thanks.

**Pull request merged**
