### PR TITLE
support spring boot 2

### PR DESCRIPTION
**Pull request by RutledgePaulV**

### CODE REVIEW

**Comment by RutledgePaulV** [comment]
Probably needs to wait until there's a stable 2.0.0 but thought I'd get a jump start. I could use some help with what needs to change in the readme and any management for JDK 7 deprecation, etc.

**Comment by platan** [comment]
@RutledgePaulV Thanks for your contribution! Great idea to prepare for Spring Boot before final release. 
This badge shows latest version (tag) of Spring Boot [GitHub tag]() 
We should probably add some info in README about handlebars-spring-boot-starter - spring boot version compatibility.

**Comment by platan** [comment]
I will let you know when a new version is available. This should take up to several days.

**Comment by platan** [comment]
@RutledgePaulV once again thanks for your contribution.

**Comment by platan** [comment]
@RutledgePaulV handlebars-spring-boot-starter 0.3.0 with Spring Boot 2.0 support is available http://repo1.maven.org/maven2/pl/allegro/tech/boot/handlebars-spring-boot-starter/0.3.0/

**Pull request merged**
